version: "3.8"
services:

  ####### Tracking service

  tracking_service:
    hostname: tracking_service
    build: 
        context: .
        dockerfile: Dockerfile_tracking_service
    env_file:
      - docker-compose-conf/tracking-service.env
    networks:
      - net
    depends_on:
      - mariadb-galera-0
      - kafka
    restart: on-failure
   
  nginx_load_balancer:
    image: nginx:latest
    volumes:
      - ./docker-compose-conf/nginx-load-balancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tracking_service
    ports:
      - "8080:8080"
    networks:
      - net

  ####### mysql cluster
      
  mariadb-galera-0:
    container_name: mariadb-cluster
    image: docker.io/bitnami/mariadb-galera:10.3
    env_file:
      - docker-compose-conf/mariadb-cluster.env
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - net

  mariadb-galera:
    image: docker.io/bitnami/mariadb-galera:10.3
    command:
      - bash
      - -ec
      - |
          sleep 20
          exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
    env_file:
      - docker-compose-conf/mariadb-galera.env
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      start_period: 20s
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - mariadb-galera-0
    networks:
      - net


  ###### Kafka 
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    env_file:
      - docker-compose-conf/zookeeper.env
    networks:
      - net
  
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file:
      - docker-compose-conf/kafka.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  
  init-kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic users-tracked --replication-factor 1 --partitions 1 --config retention.ms=3600000 --config cleanup.policy=compact

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "
    networks:
      - net

networks:
  net: